<a href="https://colab.research.google.com/github/crerarc/Python/blob/main/playbook_python_intermed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Playbook - Intermediate

# License

 python_playbook_intermed.py
 
 Copyright 2022 Crerar Christie <crerarc03@gmail.com>
 
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>


In [ ]:
#@title Introspection
# Built in tools to help you learn about the languange
# type()
# dir()
# help()
# ----------
# callable()
# len()
# locals()
# globals()
# Other stuff...

# type
# Return values not what was expected can be common
def multiplier(x: int, y: int) -> str:
    return str(x * y)
rv = multiplier(4, 5)
print(f"return value = {rv}")
print(f"Type: {type(rv)}")

# dir()
# Returns a list of all functions and attributes available in Module
import code # 'code' used to create read-evaluatet-print-loop (REPL)
dir(code)

# help()
# Reads the docstrings in the module
# help(code)

def testfun(x: int, y:int) -> float:
    """Just a test to see what help does with a function docstring"""
    return x / y
print(testfun(8, 5))
help(testfun)

# callable()
# Used to test if an object - e.g. a function or a class, is callable
a = 5
print(f"\nIs variable a callable: {callable(a)}") # If false, likely a variable
def adder(x: int, y: int) -> None:
    pass
print(f"Is function adder callable: {callable(adder)}")

# len()
# Returns length of object (doesn't work with single value objects, e.g., int)
ltest = [5, 6, 7, 3, 2, 9]
print(f"Length of ltest: {len(ltest)}")

# locals
# Returns a dictionary of current local symbol table, use in REPL or code
def adder(x, y):
    print(f"\nLocals in adder: {locals()}")
adder(4, 5)

# globals
# Similar to locals , except globals returns module-level namespace: you get
# module level attributes, but not the arguments to the function nor their values
def adder(x, y):
    print(f"\nGlobals in adder: {globals()}")
adder(4, 5)


In [ ]:
#@title Installing packages with PIP
# Packages can be found at: https://pypi.org/
# Installing a package
# Exploring Command line options
# Installing with requirements.txt
# Upgrading a package
# Checking what's installed
# Uninstalling packages
# PIP alternatives

# Installing (need to install pip first, either via packagemanager or 
# https://pip.pypa.io/en/stable/installation/)

# python3 -m pip # Check if you have module

# pip install package_name
# Beware, don't know which Python version this pip is attached to, e.g.
# could have Python 3.6 and Python 3.8, and pip install for 3.6
# Can force with...
# python3.8 -m pip install package_name

# Multiple packages
python -m pip install package_1 package_2 package_3


In [ ]:
#@title Command line options

"""Commands
install     Install packages
download    Download packages
uninstall   Uninstall packages
freeze      Output installed packages in requirements format
list        List installed packages
show        Show info about installed packages
check       Verify installed packages have compatible dependencies
config      Manage global and local config
search      Search PyPI for packages
wheel       Build wheels from you requirements
hash        Compute hashes of package archives.
completion  A helper command used for command completion
debug       Show information for debugging
help        Show help for the commands
"""

"""General options
-h, --help  Show help
--isolated  Run pip in isolated mode
-v, --verbose Give more output
-V, --version Show version and exit
-q, --quiet Give less output
--log <PATH> Path to a verbose appending log
... and many more!
"""

# python -m pip install -h # Will show install options and package index options
# python -m pip install - r requirements.txt # dependencies are specified in requirements.txt
# python -m piop install --upgrade package_name # Upgrade package
# python3.8 -m pip list # Check what's installed

# If you installed packages using apt or brew, via an installer, they will
# not show up under pip list

# Uninstall
# pip uninstall [options] <package> #Can uninstall multiple packages at same time
# pip uninstall [options] -r <requirements file>

# pip alternatives
# Conda     https://docs.conda.io/en/latest/
# Pipenv    https://github.com/pypa/pipenv
# pipx      https://github.com/pypa/pipx
# Poetry    https://python-poetry.org/


'General options\n-h, --help  Show help\n--isolated  Run pip in isolated mode\n-v, --verbose Give more output\n-V, --version Show version and exit\n-q, --quiet Give less output\n--log <PATH> Path to a verbose appending log\n... and many more!\n'

In [ ]:
#@title Python Virtual Environments



In [ ]:
#@title Decorators
# Software design patterns that alter the functionality of of function,
# method, or class w/o having to directly use subclasses or change source of
# decorated fn.

def secret_fn(f):
    return f

@secret_fn
def myfunc():
    print("This is my secret fn.")

# @ - syntactic sugar for: myfunc = secret_fn(myfunc)
# Usually define a new fn inside the decorator & return it.
# The new fn would first do what it needs to do, then call the original fn,
# and finally process the return value.

# Decorator
def print_args(func):
    def inner_func(*args, **kwargs):
        print(args)
        print(kwargs)
        return func(*args, **kwargs) # Call the original fn w. its args
    return inner_func

@print_args
def multiply(num_a, num_b):
    return num_a * num_b

print(f"{multiply(3, 5)}\n") # (3, 5) - args, {} - kwargs, 15 the result

import time
# Decorator timing fn
def timer(methd):
    def timed(*args, **kwargs):
        t1 = time.time()
        result = methd(*args, **kwargs)
        t2 = time.time()
        print(f"{methd.__name__} took: {(t2 - t1) * 1000:10.5} ms")
        return result
    return timed

def fact_recn(n):
    if n <= 1:
        return 1
    else:
        return n * fact_recn(n - 1)

@timer
def fact_itr(n):
    lis = range(1,n+1)
    fact = 1
    for num in lis:
        fact *= num
    return(fact)


@timer
def fact_rec(n):
    return fact_recn(n)

num = 69
print(f"Factorial\nRecursive: {fact_rec(num)}\nIterative: {fact_itr(num)}")


In [ ]:
#@title Zip and unzip

# Zipped
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
zipped = list(zip(x, y)) # Zips into pairs of tuples
print(zipped)

# Unzipped
x_new, y_new = zip(*zipped)
print(x_new, "\n", y_new)

z = [(1, 2), (3, 4)]
print(*x, "\n", *z)

## Libraries

In [ ]:
#@title Library: JSON
import json

# Json to parse to python
x = '{"name":"John", "age":36, "City":"Somewhere"}'

# parse it
y = json.loads(x)

# Print results in a python dictionary
print(y["age"])

# Python to parse to json
# Python dictionary
x = {
    "name":"Fred",
    "age":30,
    "City":"SomewhereElse"
}

# Convert to json
y = json.dumps(x)

# Show output
print(y)

36
{"name": "Fred", "age": 30, "City": "SomewhereElse"}


In [ ]:
#@title Library: Sympy
import sympy as sym # library to simplify maths for machine learning

x, y = sym.symbols('x y')
gfg_exp = x**2 + 3*x

print(sym.diff(gfg_exp))
print(sym.solve(gfg_exp))
print(sym.diff(sym.sin(x), x))
print(sym.limit(1 / x, x, 0))


2*x + 3
[-3, 0]
cos(x)
oo


In [ ]:
#@title Library: Random
import random as rnd


In [ ]:
#@title Library: Numpy
import numpy as np

a = np.linspace(-np.pi, np.pi, 100)
b = np.cos(a)
c = np.sin(a)
print(f"Inner product (@): {b@c}")

x = list(range(5))
y = list(range(4, -1, -1))
xa = np.array(x)
ya = np.array(y)
za = xa * ya
print(xa,"\n",ya,"\n",za)

Inner product (@): 4.04891256782214e-16
[0 1 2 3 4] 
 [4 3 2 1 0] 
 [0 3 4 3 0]


In [ ]:
#@title Library: Scipy
from scipy.stats import norm
from scipy.integrate import quad
theta = norm()
value, error = quad(theta.pdf, -2, 2)
print(f"Integral of norm distrib btwn -2 and 2: {value}")


Integral of norm distrib btwn -2 and 2: 0.9544997361036417


In [ ]:
#@title Library: Pandas
import pandas as pd
import datetime as dt
import os
from google.colab import drive
if not(os.path.ismount('/content/gdrive')):
        drive.mount('/content/gdrive')
print(os.listdir())
ifile = "gdrive/My Drive/Colab Notebooks/Data/euroLotData.csv"
my_parser = lambda d_str: dt.datetime.strptime(d_str, "%d %b %Y")
df = pd.read_csv(ifile, parse_dates= [['D', 'M', 'Y']], date_parser = my_parser, index_col=0)
games = len(df)
draws = games * 5

# Check for rows with empty columns
is_NAN = df.isnull()
row_has_NAN = is_NAN.any(axis = 1)
rows_with_NAN = df[row_has_NAN]
print(rows_with_NAN)

# Print data frame
print(df)

# Make a vector of all numbers and how many times each appears
keys = range(1,51,1)
numbr_tots = dict.fromkeys(keys, 0)
for colm in df[['1', '2', '3', '4', '5']]:
    this_col = dict(df[colm].value_counts())
    for kv in this_col:
        numbr_tots[kv] += this_col[kv]

freqs = {key:val/draws for (key,val) in numbr_tots.items()}



In [ ]:
#@title Library: Matplotlib
%matplotlib inline
# Plot size w/o Figure call: plt.rcParams["figure.figsize"] = (12, 6)
import matplotlib.pyplot as plt
fig = plt.figure()
fig.figsize = (6, 3)
lists = sorted(freqs.items())
x, y = zip(*lists)
xp = [1, 50]
yp = [0.02, 0.02]
plt.plot(x, y, label = "Actual", color='blue')
plt.plot(xp, yp, label = "Theory", color='red')
plt.grid()
plt.xlabel("Ball Number")
plt.ylabel(f"Freq, Draws / {draws}")
plt.show()

In [ ]:
#@title Library: Regex
#Hand ref: https://www.w3schools.com/python/python_regex.asp
import re
sentence = "This is a sentence. To test the fun. Of a sentence."
capital = re.findall("[A-Z]\w+", sentence)
print(capital)
print(re.split("\.", sentence))
print(re.sub("[.?]", '!', sentence))
x = re.search("fun.", sentence)
print(x)


In [ ]:
#@title Library: Natural Language Processing Toolkit
#import nltk
#sentence = "Hello! Good morning."
#tokens = nltk.word_tokenize(sentence)



In [ ]:
#@title Library: Pillow
# need numpy, loaded earlier
from PIL import Image
ifile = "gdrive/My Drive/Colab Notebooks/Data/landscape-prf.png"
image1 = Image.open(ifile)
print(image1.format)
print(image1.size)
print(image1.mode)
# image1.show() # regular command o/w notebook wrapper
plt.imshow(np.asarray(image1)) # command inside notebook wrapper

In [ ]:
#@title Library: Images with OpenCV
import cv2
image2 = cv2.imread(ifile, 3) # OpenCV uses BGR not RGB, so need to swap order
b, g, r = cv2.split(image2)
rgb_img2 = cv2.merge([r, g, b])
#rgb_img2 = cv2.bitwise_not(rgb_img2) # Negagive
print(rgb_img2.shape)
plt.imshow(np.asarray(rgb_img2))

In [ ]:
#@title Library: Networkx
import networkx as nx
plt.rcParams['figure.figsize'] = [10, 6]
np.random.seed(1234)

#Random Graph
p = dict((i, (np.random.uniform(0, 1), np.random.uniform(0, 1)))
    for i in range(200))
g = nx.random_geometric_graph(200, 0.12, pos=p)
pos = nx.get_node_attributes(g, 'pos')

#Find node nearest the centre point [0.5, 0.5]
dists = [(x-0.5)**2 + (y - 0.5)**2 for x, y in list(pos.values())]
ncentre = np.argmin(dists)

#Plot graph
p = nx.single_source_shortest_path_length(g, ncentre)
plt.figure()
nx.draw_networkx_edges(g, pos, alpha = 0.4)
nx.draw_networkx_nodes(g,
                       pos,
                       nodelist = list(p.keys()),
                       node_size = 120, alpha = 0.5,
                       node_color = list(p.values()),
                       cmap = plt.cm.jet_r)
plt.show()
    

In [ ]:
#@title Library: Scikit learn
# https://scikit-learn.org/stable/

## Applicaitons

In [ ]:
#@title Machine Learning
# https://www.w3schools.com/python/python_ml_getting_started.asp

In [ ]:
#@title MySQL
# https://www.w3schools.com/python/python_mysql_getstarted.asp

## Practice

|Sort|Reference|
|----|----|
| Leetcode ||
| Kaggle ||
| Euler ||
| Projects| Calculator |
|| Matrix multiplication w/o library |
|| Abaqus file checker |
|| Build a game with pygame |
|| Text to speech and OCR |
|| Virtual assistant (JARVIS) |
